language: node_js
sudo: false
node_js:
  - v0.10
  - v0.12
  - v4
  - v5
  - v6

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@3
install:
  - npm install

after_success:
  - npm run coveralls
  - npm run semantic-release
